import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { toolErrorFrom } from "../toolResult.js";
import { consumeSession } from "./start-pair-qr.js";
import type { PairStatus } from "../pairing.js";

type OrchestratorFn = (args: { serviceName: string; password: string; timeoutMs: number }) => Promise<PairStatus>;

const realOrchestrator: OrchestratorFn = async ({ serviceName, password, timeoutMs }) => {
  const { discoverPairingPort, discoverConnectByHost } = await import("../mdns.js");
  const { runAdb } = await import("../adb.js");

  let host: string;
  let port: number;
  try {
    const r = await discoverPairingPort(serviceName, timeoutMs);
    host = r.host;
    port = r.port;
  } catch (err) {
    const code = (err as { code?: string }).code;
    if (code === "MDNS_UNAVAILABLE") return { kind: "error", reason: "mDNS daemon unavailable" };
    return { kind: "timeout" };
  }

  try {
    await runAdb(["pair", `${host}:${port}`, password]);
  } catch (err) {
    const e = err as { stderr?: string; message?: string };
    return { kind: "error", reason: (e.stderr && e.stderr.trim()) || e.message || "adb pair failed", rawAdbError: e.stderr };
  }

  let connectHost = host;
  let connectPort = port;
  try {
    const r = await discoverConnectByHost(host, 10_000);
    connectHost = r.host;
    connectPort = r.port;
  } catch {
    // Fall through with pairing host:port — adb connect will surface a clean error.
  }

  try {
    await runAdb(["connect", `${connectHost}:${connectPort}`]);
  } catch (err) {
    const e = err as { stderr?: string; message?: string };
    return { kind: "error", reason: (e.stderr && e.stderr.trim()) || e.message || "adb connect failed", rawAdbError: e.stderr };
  }

  const { stdout } = await runAdb(["devices", "-l"]);
  const serial = `${connectHost}:${connectPort}`;
  for (const line of stdout.split(/\r?\n/)) {
    if (!line.includes(serial)) continue;
    const parts = line.trim().split(/\s+/);
    if (parts[1] !== "device") continue;
    const modelMatch = parts.find((p) => p.startsWith("model:"));
    return { kind: "success", serial: parts[0], model: modelMatch ? modelMatch.slice(6) : "Unknown" };
  }
  return { kind: "error", reason: `Paired ${serial} but device not ready.` };
};

let orchestratorImpl: OrchestratorFn = realOrchestrator;
export function __setOrchestratorForTest(fn: OrchestratorFn | null): void {
  orchestratorImpl = fn ?? realOrchestrator;
}

const ERROR_CODE_BY_STATUS: Record<string, string> = {
  timeout: "PAIRING_TIMEOUT",
  error: "ADB_PAIR_FAILED",
};

export interface WaitForPairArgs {
  service_name: string;
  timeout_ms?: number;
}

export async function handleWaitForPair(args: WaitForPairArgs): Promise<{
  content: Array<{ type: "text"; text: string }>;
  structuredContent: {
    paired: boolean;
    serial?: string;
    model?: string;
    error?: { code: string; message: string };
  };
}> {
  const session = consumeSession(args.service_name);
  if (!session) {
    return {
      content: [{ type: "text", text: `No active pairing session for '${args.service_name}'.` }],
      structuredContent: {
        paired: false,
        error: { code: "UNKNOWN_SERVICE", message: "service_name does not match a recent start_pair_qr call." },
      },
    };
  }

  const timeoutMs = args.timeout_ms ?? 60_000;
  const status = await orchestratorImpl({
    serviceName: args.service_name,
    password: session.password,
    timeoutMs,
  });

  if (status.kind === "success") {
    return {
      content: [{ type: "text", text: `Paired ${status.serial} (${status.model}).` }],
      structuredContent: { paired: true, serial: status.serial, model: status.model },
    };
  }
  if (status.kind === "timeout") {
    return {
      content: [{ type: "text", text: "Pairing timed out before the phone scanned the QR." }],
      structuredContent: {
        paired: false,
        error: { code: "PAIRING_TIMEOUT", message: `No phone scanned within ${timeoutMs}ms.` },
      },
    };
  }
  const reason = status.kind === "error" ? status.reason : `Unexpected pairing status: ${status.kind}`;
  return {
    content: [{ type: "text", text: `Pairing failed: ${reason}` }],
    structuredContent: {
      paired: false,
      error: { code: ERROR_CODE_BY_STATUS[status.kind] ?? "ADB_PAIR_FAILED", message: reason },
    },
  };
}

export function registerWaitForPair(server: McpServer): void {
  server.registerTool(
    "wait_for_pair",
    {
      title: "Wait for a phone to scan a pairing QR",
      description:
        "Block until a phone scans a QR generated by start_pair_qr and the pair + connect " +
        "handshake completes. Returns { paired, serial?, model? } on success or { paired: false, error } on " +
        "timeout/failure. Default timeout 60s.",
      inputSchema: {
        service_name: z.string().describe("The service_name returned by a prior start_pair_qr call."),
        timeout_ms: z.number().int().positive().optional().describe("Timeout in milliseconds. Default 60000."),
      },
      outputSchema: {
        paired: z.boolean(),
        serial: z.string().optional(),
        model: z.string().optional(),
        error: z.object({ code: z.string(), message: z.string() }).optional(),
      },
      annotations: { readOnlyHint: false, openWorldHint: true },
    },
    async (args) => {
      try {
        return await handleWaitForPair(args as WaitForPairArgs);
      } catch (err) {
        return toolErrorFrom(err);
      }
    }
  );
}
